services:
  ft_server:
    container_name: bisheng-ft-server
    image: cr.dataelem.com/dataelement/bisheng-ft-npu:v0.5.0-arm64
#    shm_size: "4g"
    volumes:
      - /etc/hccn.conf:/etc/hccn.conf
      - /usr/local/Ascend/driver:/usr/local/Ascend/driver
      - /etc/ascend_install.info:/etc/ascend_install.info
      - /var/log/npu/dump:/var/log/npu/dump
      - /var/log/npu/slog:/var/log/npu/slog
      - /var/log/npu:/usr/slog
      - /usr/local/sbin:/usr/local/sbin
      - /var/log/npu/profiling:/var/log/npu/profiling
      - /usr/local/Ascend/add-ons:/usr/local/Ascend/add-ons
      - /usr/local/dcmi:/usr/local/dcmi
      - /usr/local/sbin/npu-smi:/usr/local/sbin/npu-smi
      - ./bisheng-ft/config.yaml:/opt/bisheng-ft/sft_server/config.yaml
      - /home/data2/llm-models:/opt/bisheng-ft/models/model_repository
      - ./data/finetune_output:/opt/bisheng-ft/finetune_output
    ports:
      - "8000:8000"
    environment:
      - SYSTEM_ENV=NPU
    ipc: host
    tty: true
    stdin_open: true
    command: bash ./start-sft-server.sh
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
      start_period: 30s
      interval: 90s
      timeout: 30s
      retries: 3
    devices:
      - /dev/davinci0
      - /dev/davinci1
      - /dev/davinci2
      - /dev/davinci3
      - /dev/davinci4
      - /dev/davinci5
      - /dev/davinci6
      - /dev/davinci7
      - /dev/davinci_manager
      - /dev/devmm_svm
      - /dev/hisi_hdc
    restart: unless-stopped
