services:
  ft_server:
    container_name: bisheng-ft-server
    image: dataelement/bisheng-ft:latest
    ports:
      - "8000:8000"
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/config/config_ft.yaml:/opt/bisheng-ft/sft_server/config.yaml  # 服务启动所需的配置文件地址
      - /home/public/llm:/opt/bisheng-ft/models/model_repository # 配置和RT服务同样的大模型目录
      - /home/public/finetune_output:/opt/bisheng-ft/finetune_output # 训练期间的输出的模型和训练日志目录
    security_opt:
      - seccomp:unconfined
    command: bash start-sft-server.sh # 启动服务
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      start_period: 30s
      interval: 90s
      timeout: 30s
      retries: 3
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]