services:
  sft_server:
    container_name: bisheng-ft-server
    image: dataelement/bisheng-ft:latest
    ports:
      - "8000:8000"
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/bisheng/config/config.yaml:/opt/bisheng-rt/sft_server/config.yaml  # 配置配置文件地址
      - ${DOCKER_VOLUME_DIRECTORY:-.}/data/models:/opt/bisheng-rt/models # 配置和RT服务同样的大模型目录
    security_opt:
      - seccomp:unconfined
    command: sh start-sft-server.sh # 启动服务
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      start_period: 30s
      interval: 90s
      timeout: 30s
      retries: 3
