# Celery 的broker配置。ft指令执行结果存储redis。
# 密码加密规则和backend一致, 暂只支持单节点
redis_url: "redis://:gAAAAABl0cIKZe2XooAzwuWgq1Ai26_Th4TDvbKDJ-1Jap1CGaiotQb7HyF-iG7-ksJe3B8rtQQCztAddTJHoBpUB2PiUgvlOg==@127.0.0.1:6379/5"
